before_commands:
    - "composer update --prefer-source"

tools:
    external_code_coverage:
        enabled: true
        timeout: 600
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["library/*", "tests/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["docs/*", "tests", "vendor", "website"]
    php_cs_fixer:
        enabled: true
        config:
            level: psr2
        filter:
            paths: ["library/*", "tests/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["docs/*", "vendor", "website"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["library/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["docs/*", "tests", "vendor", "website"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["library/*", "tests/*"]
