before_commands:
    - "composer update --prefer-source"

tools:
    external_code_coverage:
        enabled: true
        timeout: 600
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["library/*", "tests/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["docs/*", "tests", "vendor", "website"]
    php_cs_fixer:
        enabled: true
        config:
            level: psr2
        filter:
            paths: ["library/*", "tests/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["docs/*", "vendor", "website"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["library/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["docs/*", "tests", "vendor", "website"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["library/*", "tests/*"]
build:
    environment:
        php: '5.5.14'
    dependencies:
        before:
            - sudo apt-get install php5-dev libpcre3-dev gcc make php5-mysql
            - git clone --depth=1 git://github.com/phalcon/cphalcon.git
            - cd cphalcon/build
            - sudo ./install
            - sudo echo "extension=phalcon.so" > /etc/php5/cli/php.ini
            - sudo echo "extension=phalcon.so" > /etc/php5/apache2/php.ini
            - sudo service apache2 restart
